config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  #new users controller that permits name and image
  resources :users, controller: :users, only: :create

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  root "welcome#index"
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  get "/listings/search" => "listings#search", as: "search"
  
  resources :listings do
    resources :bookings
  end


  get "/users/current_user/bookings" => "bookings#user_bookings", as: "user_bookings"
  get "/users/:user_id/listings" => "listings#user_listings", as: "user_listings"

  get "/listings/:listing_id/bookings/:id/new_payment" => "bookings#pay", as: "new_payment"
  post '/listings/:listing_id/bookings/:id/submit_payment'=> "bookings#submit_payment", as: "submit_payment"


  # get "/welcome" => "welcome#index", as: "welcome"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :host, class_name: 'User'
  has_many :bookings
  mount_uploaders :listing_images, ListingImagesUploader

  include Bitfields
 
    bitfield :amenities, 
    :parking, 
    :wifi, 
    :disabled_access, 
    :smoking, 
    :kitchen, 
    :pool, 
    :garden, 
    :private_room, 
    :air_conditioning, 
    :event_hosting, 
    :gym, 
    :elevator

  scope :location, -> (location) {where location: location}

  # scope :smoking, -> (amenities) { select { |listing| listing.amenities == true }}  


  # => listing.select{|listing| listing.smoking ==true}

  private

  def this_is_private
    'private! dont look'
  end



end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  before_action :require_login, only: [:create,:update,:destroy,:user_listings]
  
  # show current user's listings
  def user_listings
    @listings =current_user.listings
  end
 
  def index
    @listings =Listing.all
    # @listings =current_user.listings
  end

  # show a form to create a new listing
  def new
  end

  # post and save a new listing to current user
  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save! 
      redirect_to '/listings'
    else
      render 'new'
    end
  end

  def edit
    @listing = current_user.listings.find(params[:id])
  end



  def update
    @listing = current_user.listings.find(params[:id])
 
    @listing.update(listing_params)
    redirect_to listings_path
  end

  def destroy
    @listing = current_user.listings.find(params[:id])
    if @listing.destroy
      redirect_to '/listings'
      else
      'This listing does not exist'
    end

  end


  # show a listing by id
  def show
    @listing = Listing.find(params[:id])
    @amenities = @listing.bitfield_values(:amenities).select{|key,value| value == true }
  end

  
  def search

    if params[:search_term].present?
      @listings = Listing.where("location ILIKE :search_term OR title ILIKE :search_term", search_term: "%#{params[:search_term].downcase}%")
    else
      @listings= Listing.all
    end

      if filtering_params['amenities'].present?
        filtering_params['amenities'].each do |key, value|

          @listings = @listings.public_send(key)
        end
      end

      # respond_to do |format|
      #   format.js
      # end



    render 'index'

  end

  
  private

    def listing_params
      # {"first_name"=>"asdf", "last_name"=>"asdf"}
      params.require(:listing).permit(:title, :description,:price,:location, {listing_images: []},:parking, 
      :wifi, 
      :disabled_access, 
      :smoking, 
      :kitchen, 
      :pool, 
      :garden, 
      :private_room, 
      :airconditioning, 
      :event_hosting, 
      :gym, 
      :elevator)
    end

    def filtering_params
      params.slice('amenities')
    end


  end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div class ="container mb-5">
  <br/>


  <div class="column">
    <%= form_for( Listing.new, :html => {:class => "form-control"} )do |form| %>
        <%= form.label :title, style: 'margin: 1%' %>
        <%= form.text_field :title , class: 'form-control' %>
        
          <%= form.label :price, style: 'margin: 1%' %>
          <%= form.text_field :price , class: 'form-control col-md-2' %>

          <%= form.label :location, style: 'margin: 1%' %>
          <%= form.text_field :location , class: 'form-control col-md-2' %>

        <%= form.label :description, style: 'margin: 1%'  %>
        <%= form.text_area :description, class: 'form-control', size: '50x10'%>
        <div class ="row">
          <div class ="col mt-3 ml-1 mb-1">
             <h7>Amenities</h7>
             <hr>
          </div>

         
        </div>
         
        <div class ="row">
 
          <div class="col ml-2">
            <%= form.check_box(:parking) %>
            <%= form.label :parking%>
            
            <br/>


            <%= form.check_box(:disabled_access) %>
            <%= form.label :disabled_access%>
            <br/>


            <%= form.check_box(:elevator) %>
            <%= form.label :elevator %>
            <br/>

            <%= form.check_box(:smoking) %>
            <%= form.label :smoking%>
            <br/>


          </div>





          <div class="col ml-2">

            <%= form.check_box(:wifi) %>
            <%= form.label :wifi %>
            <br/>

            <%= form.check_box(:private_room) %>
            <%= form.label :private_room %>
            <br/>

            <%= form.check_box(:kitchen) %>
            <%= form.label :kitchen%>
            <br/>

            <%= form.check_box(:air_conditioning) %>
            <%= form.label :air_conditioning%>
            <br/>

            
          </div>

          <div class="col ml-2">

            <%= form.check_box(:event_hosting) %>
            <%= form.label :event_hosting%>
            <br/>


            <%= form.check_box(:gym) %>
            <%= form.label :gym %>
            <br/>

            <%= form.check_box(:pool) %>
            <%= form.label :pool%>
            <br/>

            <%= form.check_box(:garden) %>
            <%= form.label :garden%>
            <br/>

          </div>


        </div>




        <div class ="row " >
          <div class ="col-5 mt-5 ml-4" >
            <%= form.file_field :listing_images, multiple: true %>
          </div>
          <div class ="column" >
            <%= form.submit"Create a listing", class: "btn btn-primary mt-5" %>
          </div>
        </div>
    <% end %>
  </div>


</div>

app/views/listings/edit.html.erb
<div class ="container mt-5 mb-3">
    <h1>Update Listing</h1>
</div>
  <%= render partial: 'form' %>

app/views/listings/index.html.erb
<div class = "container">
  <br/>
  <h2>Listings </h2>


  <%=form_tag({controller: "listings", action: "search"}, method: "get", class: "") do %>
      <div class ="row mb-3">
        <%= text_field_tag(:search_term, "", placeholder: "Search location", class: 'form-control col-md-5 mr-3') %>

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Filter
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

          <% Listing.bitfields[:amenities].each do |amenity, _| %>
            <div class="dropdown-item" >
             <%= check_box_tag "amenities[#{amenity.to_s}]", amenity.to_s, false, class:"" %>&nbsp
             <%= label_tag amenity.to_s.humanize, nil, class:"", style:"font-size:15px"%> &nbsp &nbsp
            </div>
          <% end %>
        </div>
      </div>
    <%= submit_tag("Search") %>
  <% end %>
</div>


  <div class="column">
 <% @listings.in_groups_of(2,false).each do|group| %> 

      <div class="row">

          <%group.each do|listing|%>

            <div class="card  w-50" style = " padding: 2%">
              <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
              <%if listing.listing_images.present?%>
                <%= image_tag listing.listing_images[0].url, class:"img-thumbnail mb-3" %>
              <%end%>
        

            
              <div class="card-body" >
                <h5 class="card-title"><strong> Title:</strong></h5>

                <%= link_to listing.title,listing_path(listing)%>
             
                <p><small class="text-muted"><strong>Posted by Host: </strong><%=listing.host.email%></small></p>
                <p class= "card-text"> <strong> Location:</strong> <%=listing.location%> </p>
                <p class= "card-text"> <strong> Description:</strong> <%=listing.description%> </p>
                <small class="text-muted"><strong> created at </strong><%=listing.created_at%></small> 
                <hr>
                <div style= "text-align: center">
                  <br/>
                  <%= button_to "view", listing_path(listing), :class=>"btn btn-info",:method => "get"%>
                </div>
              </div>
            </div>
          <%end%>    
      </div>
    
    <%end%> 
  </div>



</div>

app/views/listings/new.html.erb
<div class ="container mt-5 mb-3">
<h1>New Listing</h1>
</div>
<%= render partial: 'form' %>

app/views/listings/search.js.erb
console.log('hi')
<% @listings.each do |listing| %>
  console.log("<%= listing.title %>")
<%end%>

app/views/listings/show.html.erb
<div class= "container mb-0">
  <hr>

  <h3> <strong> Title:</strong> <%=@listing.title%></h3>
  <h5> <small class="text-muted"><strong> Posted by </strong><%=@listing.host.email%></small></h5>
  <hr>


 

<%if @listing.listing_images !=[]%>
  <div class="row mb-5">
    <div class="col-2">
    </div>

    <div class="col">
          <div id="carouselExampleIndicators" class="carousel slide"  data-ride="carousel" style=" width:100%;height:100%;" >
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">

              <% @listing.listing_images.each do |image| %>
                 <div class="carousel-item <%= 'active' if image == @listing.listing_images[0] %>" >
                    <%= image_tag image.url.to_s, class:"d-block w-100", style:"height: 100%; width:100%;
              object-fit: contain;"%>
                </div>
              <%end%>

            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

      </div>

    <div class="col-2">
    </div>

  </div>
 <hr>
<%end%>


<div class="row">
<div class="col">
    <p class= "card-text"> <strong> Location:</strong> <%=@listing.location%> <br/>
     <strong> Price per day:</strong> $ <%=@listing.price%><br/>
    <strong> Description:</strong> <%=@listing.description%></p> <br/>
      <hr>
       <strong> Amenities: </strong>
      <hr>

          <% if @amenities.present? %>
            <%@amenities.each do |key, value|%>
             <strong>  ✓  <%= key.to_s.humanize  %> </strong><br/>
            <%end%>
          <%else%>
          <p> No amenities listed. </p>
          <%end%>
</div>
 



</div>



    <br/>
    <br/>
    <div class ="row ml-1">


      
      <% if @listing.host == current_user %>
        <%=button_to "Edit listing", edit_listing_path(@listing), :class=>"btn btn-warning",:method => "get"%>
      &nbsp 
        <%=button_to 'Destroy', listing_path(@listing), :class=>"btn btn-danger",
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
      <% else %>
        <%=button_to "Book Now!", new_listing_booking_path(@listing),:class=>"btn btn-success",:method => "get"%>
      <%end%>

    </div>
  <hr> 
  <small class="text-muted"><strong> Created at:  </strong><%=@listing.created_at%></small> 
  <br/>
  <small class="text-muted"><strong> Updated at:  </strong><%=@listing.updated_at%></small> 
  <br/>
</div>

app/views/listings/user_listings.html.erb
<div class = "container">
  <br/>
  <h2>My Listings </h2>

  <div class="column">
 <% @listings.in_groups_of(2,false).each do|group| %> 

      <div class="row">

          <%group.each do|listing|%>

            <div class="card  w-50" style = " padding: 2%">
              <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->

            
              <div class="card-body" >
                <h5 class="card-title"><strong> Title:</strong></h5>

                <%= link_to listing.title,listing_path(listing)%>
             
                <p><small class="text-muted"><strong>Posted by Host: </strong><%=listing.host.email%></small></p>
                <p class= "card-text"> <strong> Location:</strong> <%=listing.location%> </p>
                <p class= "card-text"> <strong> Description:</strong> <%=listing.description%> </p>
                <small class="text-muted"><strong> created at </strong><%=listing.created_at%></small> 
                <hr>
                <div style= "text-align: center">
                  <br/>
                  <%= button_to "view", listing_path(listing), :class=>"btn btn-info",:method => "get"%>
                </div>
              </div>
            </div>
          <%end%>    
      </div>
    
    <%end%> 
  </div>



</div>