config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  #new users controller that permits name and image
  resources :users, controller: :users, only: :create

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  root "welcome#index"
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  get "/listings/search" => "listings#search", as: "search"
  
  resources :listings do
    resources :bookings
  end


  get "/users/current_user/bookings" => "bookings#user_bookings", as: "user_bookings"
  get "/users/:user_id/listings" => "listings#user_listings", as: "user_listings"

  get "/listings/:listing_id/bookings/:id/new_payment" => "bookings#pay", as: "new_payment"
  post '/listings/:listing_id/bookings/:id/submit_payment'=> "bookings#submit_payment", as: "submit_payment"


  # get "/welcome" => "welcome#index", as: "welcome"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :listing
  belongs_to :guest, class_name: 'User'
  has_one :host, through: :listing
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :uniqueness_of_date_range

  before_save :set_total_price

  def calculate_date_difference
    (self.end_date - self.start_date).to_i
  end

  def set_total_price
    self.total_price =calculate_date_difference * self.listing.price 
  end




  private
  def uniqueness_of_date_range
    errors.add(:start_date, "Booking unavailable, Start date overlaps with existing booking. Please choose another date.") unless Booking.where("? >= start_date AND ? <= end_date",
                                                            start_date, start_date).count == 0
    errors.add(:end_date,"Booking unavailable, end date overlaps with existing booking. Please choose another date." ) unless Booking.where("? >= start_date AND ? <= end_date",
                                                            end_date, end_date).count == 0
    errors.add(:base, "Booking unavailable, start date and end date overlap with existing booking. Please choose another date.") unless Booking.where("? <= start_date AND ? >= end_date",
                                                            start_date, end_date).count == 0
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :require_login, only: [:create,:index,:show,:user_bookings, :pay, :submit_pay]
  
  def user_bookings

    @bookings =current_user.bookings

  end

  #shows all bookings for the logged in guest
  def index
    @listing = Listing.find(params[:listing_id])
    @bookings =@listing.bookings
  end

  #shows a form to add a booking for the list_id in the url.
  def new
    @listing = Listing.find(params[:listing_id])
    @amenities = @listing.bitfield_values(:amenities).select{|key,value| value == true }
  end

  #submits the new booking dates for the signed in user to the db
  def create
    @booking = current_user.bookings.new(booking_params)
    @booking.listing_id = params[:listing_id]
    # @listing = Listing.find(params[:listing_id])
    if @booking.save 
      ReservationMailer.reservation_email(@booking.guest, @booking.host, @booking.id).deliver_now 
      redirect_to '/listings/'+params[:listing_id]+'/bookings'+'/'+ @booking.id.to_s+'/new_payment'
       # new_payment_path(@listing.id, @booking.id)
    else
      @listing = Listing.find(params[:listing_id])
      @booking_error = true
  
      render 'new'
    end
  end

  def show
     @booking = Booking.find(params[:id])
  end

 def pay
     @client_token = Braintree::ClientToken.generate
     @booking = Booking.find(params[:id])
  end

  def submit_payment
    # ??
    @booking = current_user.bookings.where([ "id = ?", params[:id] ]).first
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

    result = Braintree::Transaction.sale(
     :amount => @booking.total_price, #this is currently hardcoded
     :payment_method_nonce => nonce_from_the_client,
     :options => {
        :submit_for_settlement => true
      }
     )

    if result.success?
      redirect_to listing_booking_path, :flash => { :success => "Transaction successful!" }
    else
      redirect_to listing_booking_path, :flash => { :error => "Transaction failed. Please try again." }
    end
  end



  def destroy
    @booking = current_user.bookings.find(params[:id])
    if @booking.destroy
      redirect_to listing_bookings_path
      else
      'This booking does not exist'
    end
  end


  private

  def booking_params
    # {"first_name"=>"asdf", "last_name"=>"asdf"}
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<br/>
<div class= "container">
<h1>New Booking</h1>
</div>

<%= render template: 'listings/show' %>

<br/>

<% if current_user.id != @listing.host_id %>
  <div class="container mt-0">
    <%= form_for([@listing, Booking.new],:html => {:class => "form-control form-inline"} ) do |form| %>
      <%= form.label :start_date, style: 'margin: 1%'%>
      <%= form.text_field( :start_date, class: 'form-control mb-2 mr-sm-2 date_pickr') %>
    
      <%= form.label :end_date, style: 'margin: 1%' %>
      <%= form.text_field(:end_date, class: 'form-control mb-2 mr-sm-2 date_pickr') %>

      <%= form.submit "Reserve!", class: "btn btn-primary mb-2", style: 'margin-left: 5%'  %>

    <% end %>
<% end %>

</div>
<div class ="container mb-5">
  <div>
    <% if @booking_error %>
    <!-- <p> Opps! Booking you have choosen is unavailable. Please, check other dates. </p> -->
    <p> <%= flash[:notice] =  @booking.errors.messages[:start_date].first%> <p>
    <p> <%=flash[:notice] =   @booking.errors.messages[:end_date].first %> <p>
    <p> <%=flash[:notice] =   @booking.errors.messages[:base].first %> <p> 
   <%end%>
  </div>
</div>


<script type="text/javascript">
  var blocked_dates = [];

  <% @listing.bookings.each do |booking| %>
    var date_range = {
      from: "<%= booking.start_date.to_s %>",
      to: "<%= booking.end_date.to_s %>",
    };
    blocked_dates.push(date_range);
  <% end %>

  (function(){
    $('.date_pickr').flatpickr({
      dateFormat: "Y-m-d",
      disable: blocked_dates
    });
  })();
</script>

app/views/bookings/_payment_form.html.erb
<div class="demo-frame">


  <%= form_for :checkout_form, url: submit_payment_path,  html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "button" %>
    </div>
  <% end %>
</div>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>


<script>

var form = document.querySelector('#cardForm');
var submit = document.querySelector("#button");
var authorization = '<%= @client_token %>';

braintree.client.create({
  // Replace this with your own authorization.
  authorization: authorization
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
</script>

app/views/bookings/index.html.erb
<div class= "container">
  <hr>
    <h3> <strong> My Bookings </strong> </h3>
    <hr>

    <% if @bookings.first %>
      <%@bookings.each do |booking|%>

      <strong> Title: </strong><%= link_to booking.listing.title, listing_booking_path(booking.listing, booking)%>
      <br/>
      <small class="text-muted"><strong> Posted by </strong><%=booking.listing.host.email%></small>
      <br/>
      <div class ="container">
        <div class ="row mt-0">
          <strong> Description: </strong> <%=booking.listing.description%>
        </div>
        <div class ="row mt-0">
          <strong> Price per day: </strong> &nbsp $<%=booking.listing.price%> </p>
        </div>

        <div class ="row mt-0">
          <strong> Total price: </strong> &nbsp $<%=booking.total_price%> </p>
        </div>

        <div class ="row mt-0">
          <strong> Booking dates:  </strong> <p> &nbsp [<%=booking.start_date%>] to [<%=booking.end_date%>] </p>
        </div>
      </div>

      
      <br/>
      <br/>


      <small class="text-muted"><strong> created at </strong>Start Date:</strong> <%=booking.start_date%> </small>
      <br/>
      <small class="text-muted"><strong> Updated at </strong><%=booking.end_date%></small>

      <br/>
      <br/>

     
      <%= button_to 'Destroy', listing_booking_path(booking.listing, booking), :class=>"btn btn-danger",
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>

      <hr>
    <%end%>

    <% else %>
    <p> Sorry you don't have any bookings to show </p>
    <%end%>
</div>

app/views/bookings/new.html.erb
<%= render partial: 'form' %>

app/views/bookings/pay.html.erb
<div class= "container">
  <hr>
 
  <div class ="row">

    <div class ="col-5">
    <h3> <strong> Submit Payment </strong> </h3>
    </div>

     <div class= "col">
    <h3> <strong> Bookings Details</strong> </h3>
    </div>

  </div>
  <hr>
  <div class ="row">
    <div class ="column">
    </div>

    <div class="column">
      <div class = "ml-4">
    <strong>Payment due</strong>&nbsp $<%=@booking.total_price%>
  </div>

    <%= render partial: 'payment_form' %>
    </div>

    <div class ="column">
      <br/>
      <br/>
      <strong> Title: </strong><%= link_to @booking.listing.title, listing_booking_path(@booking.listing, @booking)%>

      <p><small class="text-muted"><strong> Posted by </strong><%=@booking.listing.host.email%></small></p>

      <p><strong> Description: </strong> <%=@booking.listing.description%><br/>
      <strong> Price per day: </strong> &nbsp $<%=@booking.listing.price%><br/>
      <strong> Total price: </strong> &nbsp $<%=@booking.total_price%><br/>
      <strong> Booking dates:  </strong> [<%=@booking.start_date%>] to [<%=@booking.end_date%>] </p>
      <br/>
      <br/>


      <small class="text-muted"><strong> created at </strong>Start Date:</strong> <%=@booking.start_date%> </small>
      <br/>
      <small class="text-muted"><strong> Updated at </strong><%=@booking.end_date%></small>

      <br/>
      <br/>


      </div>



  </div>
</div>

app/views/bookings/show.html.erb
<div class= "container">
  <hr>

<% flash.each do |key, value| %>
  <%if key =="error"%>
   <% key ="danger"%>
  <%end%>
  <div class="alert alert-<%= key %>"><%= value %></div>

<% end %>

  <h3> <strong> Title: </strong><%= link_to @booking.listing.title, listing_path(@booking.listing, @booking)%></h3>
  <h5> <small class="text-muted"><strong> Posted by </strong><%=@booking.listing.host.email%></small></h5>

  <strong> Description:</strong> <%=@booking.listing.description%>
  <br/>
  <br/>
  <div class ="container">
    <div class="row">
      <div class ="col-{breakpoint}-auto mr-4">
      <strong>Start Date:</strong> <%=@booking.start_date%>
      </div>
      <div class ="col-{breakpoint}-auto ">
      <strong>End Date:</strong> <%=@booking.end_date%> 
      </div>
    </div>
  </div>
<br/>

  <%= button_to 'Destroy', listing_booking_path(@booking.listing, @booking), :class=>"btn btn-danger",
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
  <hr> 
  <small class="text-muted"><strong> created at </strong><%=@booking.created_at%></small> 
  <br/>
  <small class="text-muted"><strong> Updated at </strong><%=@booking.updated_at%></small> 
  <br/>

</div>

app/views/bookings/user_bookings.html.erb
<div class= "container">
  <hr>
    <h3> <strong> My Bookings </strong> </h3>
    <hr>

    <% if @bookings.first %>
      <%@bookings.each do |booking|%>

      <strong> Title: </strong><%= link_to booking.listing.title, listing_booking_path(booking.listing, booking)%>
      <br/>
      <small class="text-muted"><strong> Posted by </strong><%=booking.listing.host.email%></small>
      <br/>
      <div class ="container">
        <div class ="row mt-0">
          <strong> Description: </strong> <%=booking.listing.description%>
        </div>
        <div class ="row mt-0">
          <strong> Price per day: </strong> &nbsp $<%=booking.listing.price%> </p>
        </div>

        <div class ="row mt-0">
          <strong> Total price: </strong> &nbsp $<%=booking.total_price%> </p>
        </div>

        <div class ="row mt-0">
          <strong> Booking dates:  </strong> <p> &nbsp [<%=booking.start_date%>] to [<%=booking.end_date%>] </p>
        </div>
      </div>

      
      <br/>
      <br/>


      <small class="text-muted"><strong> created at </strong>Start Date:</strong> <%=booking.start_date%> </small>
      <br/>
      <small class="text-muted"><strong> Updated at </strong><%=booking.end_date%></small>

      <br/>
      <br/>

     
      <%= button_to 'Destroy', listing_booking_path(booking.listing, booking), :class=>"btn btn-danger",
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>

      <hr>
    <%end%>

    <% else %>
    <p> Sorry you don't have any bookings to show </p>
    <%end%>
</div>