config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  #new users controller that permits name and image
  resources :users, controller: :users, only: :create

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  root "welcome#index"
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  get "/listings/search" => "listings#search", as: "search"
  
  resources :listings do
    resources :bookings
  end


  get "/users/current_user/bookings" => "bookings#user_bookings", as: "user_bookings"
  get "/users/:user_id/listings" => "listings#user_listings", as: "user_listings"

  get "/listings/:listing_id/bookings/:id/new_payment" => "bookings#pay", as: "new_payment"
  post '/listings/:listing_id/bookings/:id/submit_payment'=> "bookings#submit_payment", as: "submit_payment"


  # get "/welcome" => "welcome#index", as: "welcome"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @listings =Listing.all.limit(4)
  end
end

app/views/welcome/index.html.erb
<div class = "container">
  <br/>
  <h1> Welcome to PairBnB! </h1>
  <h4><em> Here Are the Most Recent Listings </em> </h4>
  <div class="card-group">

    <%@listings.each do |listing|%>
      <div class="card">

        <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
        <%if listing.listing_images !=[]%>
        <%= image_tag listing.listing_images[0].url, class:"img-thumbnail mb-3" %>
        <%end%>
        
        <div class="card-body" style = " padding: 15%">

          <h5 class="card-title"><strong> Title:</strong>
          <%= link_to listing.title, listing_path(listing)%> </h5> 
          <p><small class="text-muted"><strong>Posted by Host: </strong><%=listing.host.email%></small></p>
          <p class= "card-text"> <strong> Description:</strong> <%=listing.description%> </p>
          
          <%=button_to "Book Now!", new_listing_booking_path(listing),:class=>"btn btn-success", :method => "get"%>
        </div>

      </div>
    <%end%>


  </div>
  <br/><br/>
  <div style= "text-align: center">
   <%=button_to "View All Listings!",  listings_path(@listing),:class=>"btn btn-primary", :method => "get"%>
 </div>

</div>