config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'

  #new users controller that permits name and image
  resources :users, controller: :users, only: :create

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  root "welcome#index"
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
  get "/listings/search" => "listings#search", as: "search"
  
  resources :listings do
    resources :bookings
  end


  get "/users/current_user/bookings" => "bookings#user_bookings", as: "user_bookings"
  get "/users/:user_id/listings" => "listings#user_listings", as: "user_listings"

  get "/listings/:listing_id/bookings/:id/new_payment" => "bookings#pay", as: "new_payment"
  post '/listings/:listing_id/bookings/:id/submit_payment'=> "bookings#submit_payment", as: "submit_payment"


  # get "/welcome" => "welcome#index", as: "welcome"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <%= csrf_meta_tags %>


    <!-- Booststrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

 <!--pickr calender -->
  <!--  <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/dark.css">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <script src="https://cdn.jsdelivr.net/npm/flatpickr">
    flatpickr("#booking_start_date", {})
  </script>
 -->


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>

<!-- Nav Bar -->
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand ml-5" href="/">PairBnB</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <%= form_tag({controller: "listings", action: "search"}, method: "get", class: "form-inline my-2 my-lg-0") do %>
        <%= text_field_tag(:search_term, "", placeholder: "Search location", id: 'search_nav', class: 'form-control col-md-5 mr-2 ml-2') %>
        <%= submit_tag "Search", class: 'btn btn-outline-success my-2 my-sm-0' %>
      <% end %>

      <ul class="navbar-nav ml-5">

        <% if signed_in? -%>
          <li class="nav-item active text-muted mt-2" style= "font-size: 11px;">
            logged in as: 
            <br/>
            <%= current_user.email %>
          </li>
          <li class="nav-item active">
            <!-- insert drop down here --> 
            <li class="nav-item dropdown mt-2">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Manage your account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/users/current_user/bookings">View all your bookings </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/users/current_user/listings"> View your listings</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/listings/new">Become a host - Create New listing!</a>
              </div>
            </li>
            <!-- end drop down -->
            <li class ="mt-2">
              <%= link_to t(".sign_out"), sign_out_path, method: :delete, class:"nav-link" %>
            </li>
            <!--profile image -->
            <li class ="ml-2">
              <%= image_tag current_user.image_url.to_s, class: "rounded-circle",size: "65"%>
            </li>

          </li>
          <% else -%>
            <li class="nav-item active">
              <a class="nav-link" href="#" data-toggle="modal" data-target="#myModalSignIn">Sign in <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
            <a class="nav-link" href="#" data-toggle="modal" data-target="#myModalSignUp">Sign up <span class="sr-only">(current)</span></a>
          </li>
        <% end -%>



     


      <div class="modal fade" id ="myModalSignIn">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Sign In</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
            <!--Sign in modal html -->
              <div class="container">
                <div class ="row">
                  <a href= "/auth/facebook" class="btn btn-block btn-social btn-facebook" style="color:#FFF; margin: auto; width: 95%">
                  <span class="fa fa-facebook"></span> Sign in with Facebook
                  </a> 
                </div>
                <br/>
                <div class ="row">  
                  <div class="col">
                    <hr/>
                  </div>
                  <div class ="col-sm-1">
                    or
                  </div>
                  <div class ="col">
                    <hr/>
                  </div>
                </div>
                <div class="row">

                  <div class= "col">
                    <%= form_for :session, url: session_path do |form| %>
                      <div class ="form-group">
                        <%= form.label :email %>
                        <%= form.text_field :email, type: 'email', class: "form-control" %>
                      </div>

                      <div class ="form-group">
                      <%= form.label :password %>
                      <%= form.password_field :password , class: "form-control"%>
                      </div>

                      <div class="submit-field" style= "text-align: center">
                        <%= form.submit class: "btn btn-primary" %>
                      </div>
                      <br/>
                      <div class="other-links" style= "text-align: center">
           
                        <%= link_to t(".forgot_password?"), new_password_path %>
                        <% if Clearance.configuration.allow_sign_up? %>
                        <br/>
                        Don't Have an account?
                         <%= link_to t(".sign_up"), sign_up_path %>
                         <% end %>



                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>

            <div class="modal-footer">

            </div>
          </div>
        </div>
      </div>
      <div class="modal fade" id ="myModalSignUp">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Sign Up</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>      
            <!-- Sign up modal -->
            <div class="modal-body">
                    <div class="container">
                      <div class ="row">
                        <a href= "/auth/facebook" class="btn btn-block btn-social btn-facebook" style="color:#FFF; margin: auto; width: 95%">
                        <span class="fa fa-facebook"></span> Sign up with Facebook
                        </a> 
                      </div>
                      <br/>
                      <div class ="row">  
                        <div class="col">
                          <hr/>
                        </div>
                        <div class ="col-sm-1">
                          or
                        </div>
                        <div class ="col">
                          <hr/>
                        </div>
                      </div>
                      <div class="row">
                        <div class= "col">
                          <%= form_for User.new do |form| %>
                            <div class ="form-group">
                              <div class="text-field">
                                <%= form.label :name %>
                                <%= form.text_field :name, type: 'name', class: "form-control" %>
                              </div>
                            </div>

                            <div class ="form-group">
                              <div class="text-field">
                                <%= form.label :email %>
                                <%= form.text_field :email, type: 'email', class: "form-control" %>
                              </div>
                            </div>

                            <div class ="form-group">
                              <div class="password-field">
                                <%= form.label :password %>
                                <%= form.password_field :password, class: "form-control"  %>
                              </div>  
                            </div>

                            <div class="submit-field" style= "text-align: center">
                               <%= form.submit class: "btn btn-primary"%>
                            </div>
                              <br/>

                              <div class="other-links" style= "text-align: center">
                    
                            <div class="other-links" style= "text-align: center">
                              or click here to <%= link_to t(".sign_in"), sign_in_path %>
                            </div>
                          <% end %>
                        </div>
                      </div>
                    </div>
                        
                  </div>
            <div class="modal-footer">
            </div>
          </div>
        </div>
      </div>
    <div>
  </div>
</nav>
<!-- end nav bar -->


<!-- <div>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>
 -->
<!-- 
    <div id="header">
      <%= link_to "Sign in with Facebook", "/auth/facebook" %>
      
      <% if signed_in? -%>
        <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
      <% else -%>
       <%= link_to t(".sign_in"), sign_in_path %>
      <% end -%>
    </div> -->

<!--     <div id="flash">
      <% flash.each do |key, value| -%>
        <div id="flash_<%= key %>"><%=h value %></div>
      <% end %>
    </div>  -->

    <%= yield %>
    
  </body>
</html>